### ISSUE TITLE
Pipe Management 

### ISSUE THREAD

**Issue by io-no** [io-no/libdebug#1]
When the run method of Debugger is used repeatedly in, for example, a bruteforce, the error "too many files open" is encountered. It is hypothesized that this is due to incorrect management of the stdin and stdout PIPEs. The run uses os.execv(path, args) so it is necessary to test and verify if that is the problem. Furthermore, since it is necessary to manage the PIPEs, functions similar to recv and sendline should be implemented to interact directly with the binary.

**Comment by MrIndeciso** [comment]
![image](https://github.com/gabriele180698/libdebug/assets/6383492/a45b4380-272d-43af-9b20-908075d5b4c6)
Con questo non viene throwato l'errore, quindi il problema sta proprio in run

**Comment by MrIndeciso** [comment]
Commit 21b833e9738e6fa690452a8e29c1ae033ce2a55e might have solved this issue, as a side-effect of correctly managing the spawned process on shutdown()

**Comment by gabriele180698** [comment]
Commit 25688c5417a5035e08a0b04c12cba8fd1e6f6024 includes a first implementation of the following functions:
- recv
- recverr
- recvuntil
- recverruntil
- recvline
- recverrline
- send
- sendline
- sendafter
- sendlineafter

Working for interactive

**Comment by io-no** [comment]
Everything should work after the commit d4b27deab3ec91df5ba1faa39ee058ea5c4a8ddc
